# Expose port to access db-server directly, bypassing nginx
services:
  nginx:
    image: nginx:latest
    container_name: ${RECORD_SET_NAME:-ff}-nginx
    ports:
      - "127.0.0.1:${INTERNAL_HOST_PORT:-1235}:80"
    restart: always
    depends_on:
      - fta-fmea
      - fta-fmea-server
      - db-server
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      APP_ORIGIN: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}"
      APP_ROOT_PATH: "${APP_ROOT_PATH:-}"
      FTA_FMEA_PATH: "${FTA_FMEA_PATH:-/fta-fmea}"
      INTERNAL_FTA_FMEA_SERVER_SERVICE: "${INTERNAL_FTA_FMEA_SERVER_SERVICE:-http://fta-fmea-server:9999}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ../shared/nginx/error.html:/usr/share/nginx/html/error.html:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ../shared/nginx/images:/usr/share/nginx/html/images:ro

  fta-fmea:
    image: ghcr.io/kbss-cvut/fta-fmea-ui:latest
    container_name: ${RECORD_SET_NAME:-ff}-fta-fmea
    expose:
      - "80"
    depends_on:
      - fta-fmea-server
    environment:
      FTA_FMEA_API_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/fta-fmea-server"
      FTA_FMEA_BASENAME: "${APP_ROOT_PATH:-}${FTA_FMEA_PATH:-/fta-fmea}"
      FTA_FMEA_ADMIN_REGISTRATION_ONLY: ${ADMIN_REGISTRATION_ONLY:-false}

  fta-fmea-server:
    image: ghcr.io/kbss-cvut/fta-fmea:latest
    container_name: ${RECORD_SET_NAME:-ff}-fta-fmea-server
    expose:
      - "9999"
    depends_on:
      - db-server
    restart: always
    environment:
      appContext: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}${FTA_FMEA_PATH:-/fta-fmea}"
      REPOSITORY_URL: ${REPOSITORY_URL:-http://db-server:7200/repositories/fta-fmea}
      REPOSITORY_USERNAME: ${REPOSITORY_USERNAME:-}
      REPOSITORY_PASSWORD: ${REPOSITORY_PASSWORD:-}
      server.servlet.context-path: "/fta-fmea"


  db-server:
    build:
      context: ../shared/db-server
    image: ${RECORD_SET_NAME:-ff}-db-server
    container_name: ${RECORD_SET_NAME:-ff}-db-server
    environment:
      GDB_JAVA_OPTS: "-Dgraphdb.external-url=${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/db-server"
    expose:
      - "7200"
    restart: always
    volumes:
      - ${INIT_DATA_DIR:-../shared/db-server/import}:/root/graphdb-import:ro
      - db-server:/opt/graphdb/home

volumes:
  db-server:
